export const DOD_EXPERT = {};

/**
 * The set of Ability Scores used within the sytem.
 * @type {Object}
 */
 DOD_EXPERT.abilities = {
  "STY": "DOD_EXPERT.GRUNDEGENSKAP_STR",
  "SMI": "DOD_EXPERT.GRUNDEGENSKAP_SMI",
  "FYS": "DOD_EXPERT.GRUNDEGENSKAP_FYS",
  "STO": "DOD_EXPERT.GRUNDEGENSKAP_STO",
  "INT": "DOD_EXPERT.GRUNDEGENSKAP_INT",
  "PSY": "DOD_EXPERT.GRUNDEGENSKAP_PSY",
  "KAR": "DOD_EXPERT.GRUNDEGENSKAP_KAR"
};

DOD_EXPERT.abilityAbbreviations = {
  "STR": "DOD_EXPERT.GRUNDEGENSKAP_STRAbbr",
  "SMI": "DOD_EXPERT.GRUNDEGENSKAP_SMIAbbr",
  "FYS": "DOD_EXPERT.GRUNDEGENSKAP_FYSAbbr",
  "STO": "DOD_EXPERT.GRUNDEGENSKAP_STOAbbr",
  "INT": "DOD_EXPERT.GRUNDEGENSKAP_INTAbbr",
  "PSY": "DOD_EXPERT.GRUNDEGENSKAP_PSYAbbr",
  "KAR": "DOD_EXPERT.GRUNDEGENSKAP_KARAbbr"
};